### ISSUE TITLE
Deny video sharing

### ISSUE THREAD

**Issue by BortoAle** [SvenTiigi/YouTubePlayerKit#1]
# Motivation
> ℹ In my application i would like to show unlisted videos from youtube. I would like to prevent users from clicking on the title of the video in order to open it on youtube and be able to share it, or click directly on the share button from the player. Now I can do this disabling user interaction but than the user can't use the video controls.

# Solution
> ℹ Set the code in order that if I set ***isUserInteractionEnabled: false*** and ***showControls: true*** the controls are shown but the user can't click in the 3 dots and share the link or click in the video title and open YouTube.

**Comment by SvenTiigi** [comment]
The `YouTubePlayerKit.Configuration` includes the `playInline` parameter which can be set to `false` in order to automatically start the video in fullscreen after the video has been loaded.

```swift
YouTubePlayer(
    source: .url("https://youtube.com/...."),
    configuration: .init(
        playInline: false
    )
)
```
Reference: https://developers.google.com/youtube/player_parameters
<img width="866" alt="Bildschirmfoto 2021-10-08 um 15 47 34" src="https://user-images.githubusercontent.com/11733014/136568400-c4997c58-f47f-4389-8922-48cac77e5a3f.png">
