### ISSUE TITLE
How to set youtube player to fullscreen?

### ISSUE THREAD

**Issue by AbdulQadir0731** [SvenTiigi/YouTubePlayerKit#101]
### Is your feature request related to a problem?

Write now i am using following configuration
 let configuration = YouTubePlayer.Configuration(
        // Define which fullscreen mode should be used (system or web)
        fullscreenMode: .system,
        
        autoPlay: true
    )

### What solution would you like?

If possible provide me required configurations

### What alternatives have you considered?

i need to open youtube player on fullscreen by default

**Comment by SvenTiigi** [comment]
Hi @AbdulQadir0731,

currently this is not possible since the `allowsInlineMediaPlayback` is set to `true` as this is the most common value for this option.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/fe1c1ec340f6d79866131432ecaa190fd6bbc4cb/Sources/WebView/YouTubePlayerWebView.swift#L47-L48

Adding this property to the `YouTubePlayer.Configuration` is currently also not possible since any property of a `WKWebViewConfiguration` can not updated after it has been used to initialize a `WKWebView` (https://developer.apple.com/documentation/webkit/wkwebview/1414998-init)
