### ISSUE TITLE
adjust the pitch 

### ISSUE THREAD

**Issue by EssamSoft** [SvenTiigi/YouTubePlayerKit#21]
I'm planing to create new app to help musician 
so if there is any way to control the pitch of youtube video it will be great

**Comment by acosmicflamingo** [comment]
I'm not Sven but I bet he's going to say it's impossible because the YouTubePlayerKit framework utilizes YouTube's official API and in order to control the pitch, you need access to the actual audio data, which YouTube does not give you access to. It's technically possible to do things to get this data but all of them will break YouTube's ToS and will most likely result in an App Store rejection too. The reason speed is adjustable is because YouTube's API allows users to control this.

Now if someone actually finds a way that doesn't break their ToS, I'm all for learning about it :)

**Comment by EssamSoft** [comment]
@acosmicflamingo 
yeah I know but I'm still amazed how [Chordify](https://chordify.net/en) did that!

**Comment by acosmicflamingo** [comment]
Fascinating. There are two things that could be happening (maybe; what do I know LOL):
1. Chordify is utilizing YouTube's Data API (which requires getting permission from them and probably paying money if YouTube queries exceed a certain number). They can then change the pitch of the data however they want.
2. They are illegally downloading it (like how some youtubeTomp3 websites do it) and can be sued by YouTube for it.

If anyone knows how Chordify did it in a very easy way, please feel free to mention it :D

**Comment by SvenTiigi** [comment]
Closing this issue as @acosmicflamingo already explained that a pitch parameter is currently not part of the YouTubePlayer API.
