### ISSUE TITLE
YouTubePlayerHostingView not showing

### ISSUE THREAD

**Issue by SwiftyFlow** [SvenTiigi/YouTubePlayerKit#22]
```
let configuration = YouTubePlayer.Configuration(
            isUserInteractionEnabled: false,
            showControls: false
        )
        
        let youTubePlayer = YouTubePlayer(
            source: .url("https://www.youtube.com/watch?v=NtHOmClQE7k"),
            configuration: configuration)
        
        let player = YouTubePlayerHostingView(player: youTubePlayer)
        player.player.play()

        player.player.showStatsForNerds()

        playerView.addSubview(player)
```

I can hear it but I can't see it. Any idea?

**Comment by SvenTiigi** [comment]
Hi @SwiftyFlow,

did you add any NSLayoutConstraints or perform any kind of frame manipulation?
Because otherwise it is most likely that the size of the `YouTubePlayerHostingView` will be `(0,0)` which would explain why you can hear the sound of the YouTube video but not seeing anything on screen.

Please check the frame size via the UI Debugger or add NSLayoutConstraints to the `YouTubePlayerHostingView`

**Comment by SwiftyFlow** [comment]
Spot on! Added:

`player.frame = playerView.frame`
