### ISSUE TITLE
Volume control Issue

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#36]
Hello everyone, thank you for developing a wonderful package.
I want to use the set(:volume) function to control the volume with a slider, but even when the volume is 0,
 I can hear the sound without changing it.

**Comment by SvenTiigi** [comment]
Hi @yongbeomkwak,

Sadly this is an issue/limitation of the YouTube Player JavaScript iFrame API in the context of a WKWebView.
Please see this issue on the official youtube-ios-player-helper repo: https://github.com/youtube/youtube-ios-player-helper/issues/20

Maybe adding some kind of deprecation warning to the `setVolume` API of the YouTubePlayerKit would be beneficial to indicate that this function is part of the YouTubePlayer iFrame API but will have no effect when calling due to the limitation of the WKWebView APIs.

**Comment by yongbeomkwak** [comment]
> Hi @yongbeomkwak,
> 
> Sadly this is an issue/limitation of the YouTube Player JavaScript iFrame API in the context of a WKWebView. Please see this issue on the official youtube-ios-player-helper repo: [youtube/youtube-ios-player-helper#20](https://github.com/youtube/youtube-ios-player-helper/issues/20)
> 
> Maybe adding some kind of deprecation warning to the `setVolume` API of the YouTubePlayerKit would be beneficial to indicate that this function is part of the YouTubePlayer iFrame API but will have no effect when calling due to the limitation of the WKWebView APIs.

@SvenTiigi  Thank you sir ,   I don't know that IOS only can control volume by hardware volume button.. because 
I started learning ios a month ago
