### ISSUE TITLE
Video quality seems capped at 720p

### ISSUE THREAD

**Issue by frlefebvre** [SvenTiigi/YouTubePlayerKit#56]
### What happened?

When playing videos, the maximum quality available is 720p.

### What are the steps to reproduce?

1. Setup the player with default configuration for a video that has (at least) 1080p quality available on YouTube
2. Press play
3. Open the settings for the video
4. Maximum selectable quality is 720p. playbackQualityPublisher also reports back hd720

### What is the expected behavior?

I would expect videos that have 1080p available to show the option and play at the highest quality available. The quality publisher seems to have a case for it so maybe there's a problem on my end though?

**Comment by SvenTiigi** [comment]
Hi @frlefebvre,

Thanks for opening up an issue.
The issue you described is a main thread checker warning caused by the underlying `WKWebView`

- https://developer.apple.com/forums/thread/714467?answerId=734799022#734799022

> The poor interaction between WKWebView, Security framework, and this Xcode feature is a known issue (r. 94019453). We plan to address it at some point but I don’t have any info to share as to when that’ll happen.

<img width="883" alt="Bildschirm­foto 2023-01-29 um 17 23 51" src="https://user-images.githubusercontent.com/11733014/215340028-490a1df9-801c-40e6-9a95-80d3598c4a05.png">

**Comment by SvenTiigi** [comment]
Hi @frlefebvre,

The `YouTubePlayerKit` makes use of the official YouTube Player iFrame JavaScript API where some quality options are not available.

- https://support.google.com/youtube/answer/6322658?visit_id=638106065540169701-3128763685&p=missing_quality&rd=1

<img width="746" alt="Bildschirm­foto 2023-01-29 um 17 31 40" src="https://user-images.githubusercontent.com/11733014/215340384-ff16447b-53ca-432d-8a6f-bbe7ccbaa930.png">
